version: "3"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/go/src/app/
